apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment3
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:latest
        command: ["/bin/sh", "-c", " mkdir /usr/local/apache2/htdocs/apache2 && cp  /usr/local/apache2/htdocs/index.html  /usr/local/apache2/htdocs/apache2/ && echo '<h1>Ibraim Pushka</h1>' > /usr/local/apache2/htdocs/apache2/index.html &&  . /usr/local/bin/httpd-foreground" ] 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-apachee2
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80